language: ruby
bundler_args: --without tools
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - ruby-head
  - ree
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - rbx-18mode
  - rbx-19mode
matrix:
  allow_failures:
    - rvm: jruby-head
notifications:
  recipients:
    - remy@rymai.me
